export const usersList = [
    {
        id: 1,
        username: 'Sid2024',
        password: 'Sid2024',
        firstname: 'Siddharth',
        lastname: 'Bhat',
        phone: 8208465375,
        email: 'dbgt4531@gmail.com',
        institute: 'ICS',
        programme: 'MCA',
        gr_no: '5875876765768',
        year: '2024',
        status: 1,
        createdAt: '2024-01-01T11:19:37Z'
    },
    {
        id: 2,
        username: 'Ruchi2024',
        password: 'Ruchi2024',
        firstname: 'Ruchita',
        lastname: 'Ganacharya',
        phone: 9765474787,
        email: 'ruchi4gana@gmail.com',
        institute: 'IOM',
        programme: 'MMS',
        gr_no: '6745378523458',
        year: '2024',
        status: 1,
        createdAt: '2024-01-01T11:19:37Z'
    },
    {
        id: 3,
        username: 'JohnDoe',
        password: 'JohnDoe123',
        firstname: 'John',
        lastname: 'Doe',
        phone: 1234567890,
        email: 'johndoe@gmail.com',
        institute: 'XYZ University',
        programme: 'Computer Science',
        gr_no: '123456789',
        year: '2023',
        status: 1,
        createdAt: '2024-01-02T14:30:45Z'
    },
    {
        id: 4,
        username: 'Alice2023',
        password: 'Alice2023',
        firstname: 'Alice',
        lastname: 'Johnson',
        phone: 9876543210,
        email: 'alice.johnson@email.com',
        institute: 'ABC College',
        programme: 'Engineering',
        gr_no: '987654321',
        year: '2023',
        status: 1,
        createdAt: '2024-01-02T14:30:45Z'
    },
    {
        id: 5,
        username: 'TechGeek',
        password: 'Tech123',
        firstname: 'Tech',
        lastname: 'Geek',
        phone: 5551234567,
        email: 'techgeek@email.com',
        institute: 'Tech Institute',
        programme: 'IT',
        gr_no: '555555555',
        year: '2022',
        status: 1,
        createdAt: '2024-01-03T09:15:22Z'
    },
    {
        id: 6,
        username: 'SarahSmith',
        password: 'Sarah2022',
        firstname: 'Sarah',
        lastname: 'Smith',
        phone: 9998887777,
        email: 'sarah.smith@email.com',
        institute: 'University of Arts',
        programme: 'Fine Arts',
        gr_no: '999999999',
        year: '2022',
        status: 1,
        createdAt: '2024-01-03T09:15:22Z'
    },
    {
        id: 7,
        username: 'MarkC',
        password: 'MarkC123',
        firstname: 'Mark',
        lastname: 'Carter',
        phone: 3334445555,
        email: 'mark.carter@email.com',
        institute: 'Science College',
        programme: 'Physics',
        gr_no: '333333333',
        year: '2021',
        status: 1,
        createdAt: '2024-01-04T17:40:12Z'
    },
    {
        id: 8,
        username: 'EmmaJohnson',
        password: 'Emma123',
        firstname: 'Emma',
        lastname: 'Johnson',
        phone: 6667778888,
        email: 'emma.johnson@email.com',
        institute: 'Engineering University',
        programme: 'Mechanical Engineering',
        gr_no: '666666666',
        year: '2021',
        status: 1,
        createdAt: '2024-01-04T17:40:12Z'
    },
    {
        id: 9,
        username: 'TechEnthusiast',
        password: 'Tech456',
        firstname: 'Tech',
        lastname: 'Enthusiast',
        phone: 1112223333,
        email: 'tech.enthusiast@email.com',
        institute: 'Tech School',
        programme: 'Computer Engineering',
        gr_no: '111111111',
        year: '2023',
        status: 1,
        createdAt: '2024-01-05T08:55:30Z'
    },
    {
        id: 10,
        username: 'EllaM',
        password: 'EllaM2023',
        firstname: 'Ella',
        lastname: 'Meyer',
        phone: 4445556666,
        email: 'ella.meyer@email.com',
        institute: 'Arts Academy',
        programme: 'Drama',
        gr_no: '444444444',
        year: '2023',
        status: 1,
        createdAt: '2024-01-05T08:55:30Z'
    },
    // Add more user data
    {
        id: 11,
        username: 'TechWizard',
        password: 'Wizard123',
        firstname: 'Tech',
        lastname: 'Wizard',
        phone: 7778889999,
        email: 'tech.wizard@email.com',
        institute: 'Tech Institute',
        programme: 'Software Engineering',
        gr_no: '777777777',
        year: '2022',
        status: 1,
        createdAt: '2024-01-06T12:10:18Z'
    },
    {
        id: 12,
        username: 'GraceP',
        password: 'Grace2022',
        firstname: 'Grace',
        lastname: 'Parker',
        phone: 2223334444,
        email: 'grace.parker@email.com',
        institute: 'Business School',
        programme: 'MBA',
        gr_no: '222222222',
        year: '2022',
        status: 1,
        createdAt: '2024-01-06T12:10:18Z'
    },
    {
        id: 13,
        username: 'ChrisEvansFan',
        password: 'Chris123',
        firstname: 'Chris',
        lastname: 'Fanatic',
        phone: 8889990000,
        email: 'chris.fanatic@email.com',
        institute: 'Film School',
        programme: 'Film Production',
        gr_no: '888888888',
        year: '2021',
        status: 1,
        createdAt: '2024-01-07T20:25:45Z'
    },
    {
        id: 14,
        username: 'OliviaW',
        password: 'Olivia2021',
        firstname: 'Olivia',
        lastname: 'Williams',
        phone: 1110002222,
        email: 'olivia.williams@email.com',
        institute: 'Medical College',
        programme: 'Medicine',
        gr_no: '111111111',
        year: '2021',
        status: 1,
        createdAt: '2024-01-07T20:25:45Z'
    },
    {
        id: 15,
        username: 'GuitarHero',
        password: 'Guitar456',
        firstname: 'Guitar',
        lastname: 'Hero',
        phone: 5554443333,
        email: 'guitar.hero@email.com',
        institute: 'Music School',
        programme: 'Guitar Performance',
        gr_no: '555555555',
        year: '2023',
        status: 1,
        createdAt: '2024-01-08T14:50:32Z'
    },
    {
        id: 16,
        username: 'SophiaR',
        password: 'Sophia2023',
        firstname: 'Sophia',
        lastname: 'Roberts',
        phone: 9998887777,
        email: 'sophia.roberts@email.com',
        institute: 'Law School',
        programme: 'Law',
        gr_no: '999999999',
        year: '2023',
        status: 1,
        createdAt: '2024-01-08T14:50:32Z'
    },
    {
        id: 17,
        username: 'TechInnovator',
        password: 'Innovate123',
        firstname: 'Tech',
        lastname: 'Innovator',
        phone: 3332221111,
        email: 'tech.innovator@email.com',
        institute: 'Tech University',
        programme: 'Innovation Studies',
        gr_no: '333333333',
        year: '2022',
        status: 1,
        createdAt: '2024-01-09T09:05:10Z'
    },
    {
        id: 18,
        username: 'LilyM',
        password: 'Lily2022',
        firstname: 'Lily',
        lastname: 'Martin',
        phone: 6667778888,
        email: 'lily.martin@email.com',
        institute: 'Art and Design College',
        programme: 'Graphic Design',
        gr_no: '666666666',
        year: '2022',
        status: 1,
        createdAt: '2024-01-09T09:05:10Z'
    },
    {
        id: 19,
        username: 'TechExplorer',
        password: 'Explore456',
        firstname: 'Tech',
        lastname: 'Explorer',
        phone: 4445556666,
        email: 'tech.explorer@email.com',
        institute: 'Tech Institute',
        programme: 'Computer Science',
        gr_no: '444444444',
        year: '2023',
        status: 1,
        createdAt: '2024-01-10T18:20:57Z'
    },
    {
        id: 20,
        username: 'NoahT',
        password: 'Noah2023',
        firstname: 'Noah',
        lastname: 'Thompson',
        phone: 1112223333,
        email: 'noah.thompson@email.com',
        institute: 'Engineering College',
        programme: 'Civil Engineering',
        gr_no: '111111111',
        year: '2023',
        status: 1,
        createdAt: '2024-01-10T18:20:57Z'
    }
];

export const mediaList = [
    {
        id: 1,
        title: 'Perfect',
        artists: [5],
        file_path: 'this/is/dummy/path',
        category: 2,
        lyricist: 'Ed Sheeran',
        director: 'Ed Sheeran',
        views_count: 34,
        likes_count: 12,
        dislikes_count: 5,
        tags: ['Song', 'Mp4', 'American']
    },
    {
        id: 2,
        title: 'Attention',
        artists: [3, 9],
        file_path: 'this/is/dummy/path',
        category: 1,
        lyricist: 'Charlie Puth',
        director: 'Charlie Puth',
        views_count: 98,
        likes_count: 16,
        dislikes_count: 2,
        tags: ['Songs', 'Mp4', 'Album']
    },
    {
        id: 3,
        title: 'Shape of You',
        artists: [7],
        file_path: 'this/is/dummy/path',
        category: 8,
        lyricist: 'Ed Sheeran',
        director: 'Ed Sheeran',
        views_count: 45,
        likes_count: 20,
        dislikes_count: 10,
        tags: ['Song', 'Mp4', 'Pop']
    },
    {
        id: 4,
        title: 'See You Again',
        artists: [2, 8],
        file_path: 'this/is/dummy/path',
        category: 4,
        lyricist: 'Wiz Khalifa',
        director: 'Director X',
        views_count: 120,
        likes_count: 50,
        dislikes_count: 15,
        tags: ['Songs', 'Mp4', 'Rap']
    },
    {
        id: 5,
        title: 'Havana',
        artists: [10, 12],
        file_path: 'this/is/dummy/path',
        category: 6,
        lyricist: 'Camila Cabello',
        director: 'Dave Meyers',
        views_count: 80,
        likes_count: 30,
        dislikes_count: 5,
        tags: ['Songs', 'Latin', 'Pop']
    },
    {
        id: 6,
        title: 'Believer',
        artists: [15],
        file_path: 'this/is/dummy/path',
        category: 10,
        lyricist: 'Dan Reynolds',
        director: 'Matt Eastin',
        views_count: 110,
        likes_count: 40,
        dislikes_count: 10,
        tags: ['Rock', 'Alternative']
    },
    {
        id: 7,
        title: 'Despacito',
        artists: [18, 20],
        file_path: 'this/is/dummy/path',
        category: 3,
        lyricist: 'Luis Fonsi',
        director: 'Carlos Perez',
        views_count: 150,
        likes_count: 70,
        dislikes_count: 15,
        tags: ['Songs', 'Latin', 'Reggaeton']
    },
    {
        id: 8,
        title: 'Rolling in the Deep',
        artists: [6],
        file_path: 'this/is/dummy/path',
        category: 7,
        lyricist: 'Adele',
        director: 'Sam Brown',
        views_count: 200,
        likes_count: 80,
        dislikes_count: 10,
        tags: ['Songs', 'Pop', 'Soul']
    },
    {
        id: 9,
        title: 'Sicko Mode',
        artists: [13, 17],
        file_path: 'this/is/dummy/path',
        category: 5,
        lyricist: 'Travis Scott',
        director: 'Dave Meyers',
        views_count: 180,
        likes_count: 60,
        dislikes_count: 20,
        tags: ['Songs', 'Hip-Hop', 'Rap']
    },
    {
        id: 10,
        title: 'Waka Waka',
        artists: [22],
        file_path: 'this/is/dummy/path',
        category: 9,
        lyricist: 'Shakira',
        director: 'Marcus Raboy',
        views_count: 120,
        likes_count: 50,
        dislikes_count: 5,
        tags: ['Songs', 'Pop', 'World']
    },
    // Add more media data
    {
        id: 11,
        title: 'Radioactive',
        artists: [14],
        file_path: 'this/is/dummy/path',
        category: 2,
        lyricist: 'Imagine Dragons',
        director: 'Mark Pellington',
        views_count: 80,
        likes_count: 30,
        dislikes_count: 5,
        tags: ['Rock', 'Alternative']
    },
    {
        id: 12,
        title: 'Uptown Funk',
        artists: [11, 19],
        file_path: 'this/is/dummy/path',
        category: 8,
        lyricist: 'Bruno Mars',
        director: 'Mark Ronson',
        views_count: 160,
        likes_count: 70,
        dislikes_count: 10,
        tags: ['Songs', 'Pop', 'Funk']
    },
    {
        id: 13,
        title: 'Counting Stars',
        artists: [16],
        file_path: 'this/is/dummy/path',
        category: 6,
        lyricist: 'OneRepublic',
        director: 'James Lees',
        views_count: 130,
        likes_count: 50,
        dislikes_count: 5,
        tags: ['Songs', 'Pop', 'Rock']
    },
    {
        id: 14,
        title: 'Roar',
        artists: [21],
        file_path: 'this/is/dummy/path',
        category: 1,
        lyricist: 'Katy Perry',
        director: 'Grady Hall',
        views_count: 100,
        likes_count: 40,
        dislikes_count: 5,
        tags: ['Songs', 'Pop', 'Anthemic']
    },
    {
        id: 15,
        title: 'Bad Romance',
        artists: [4],
        file_path: 'this/is/dummy/path',
        category: 3,
        lyricist: 'Lady Gaga',
        director: 'Francis Lawrence',
        views_count: 180,
        likes_count: 70,
        dislikes_count: 15,
        tags: ['Songs', 'Pop', 'Dance']
    },
    {
        id: 16,
        title: 'All of Me',
        artists: [23],
        file_path: 'this/is/dummy/path',
        category: 4,
        lyricist: 'John Legend',
        director: 'Nabil Elderkin',
        views_count: 150,
        likes_count: 60,
        dislikes_count: 10,
        tags: ['Songs', 'Pop', 'Love']
    },
    {
        id: 17,
        title: 'Thunder',
        artists: [13],
        file_path: 'this/is/dummy/path',
        category: 7,
        lyricist: 'Imagine Dragons',
        director: 'Joseph Kahn',
        views_count: 120,
        likes_count: 50,
        dislikes_count: 5,
        tags: ['Rock', 'Alternative']
    },
    {
        id: 18,
        title: 'Firework',
        artists: [21],
        file_path: 'this/is/dummy/path',
        category: 9,
        lyricist: 'Katy Perry',
        director: 'Dave Meyers',
        views_count: 100,
        likes_count: 40,
        dislikes_count: 5,
        tags: ['Songs', 'Pop', 'Anthemic']
    },
    {
        id: 19,
        title: 'Take Me to Church',
        artists: [24],
        file_path: 'this/is/dummy/path',
        category: 5,
        lyricist: 'Hozier',
        director: 'Brendan Canty',
        views_count: 120,
        likes_count: 50,
        dislikes_count: 5,
        tags: ['Songs', 'Pop', 'Alternative']
    },
    {
        id: 20,
        title: 'Can\'t Stop the Feeling!',
        artists: [11],
        file_path: 'this/is/dummy/path',
        category: 10,
        lyricist: 'Justin Timberlake',
        director: 'Mark Romanek',
        views_count: 200,
        likes_count: 80,
        dislikes_count: 10,
        tags: ['Songs', 'Pop', 'Feel-Good']
    }
];